app = "reflectdb-tetris"
primary_region = "sjc"
kill_signal = "SIGTERM"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
PORT = "8080"
TETRIS_DB_PATH = "/app/examples/tetris/tetris.db"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
persist_rootfs = "restart"
